# Generated by Django 6.1.2 on 2026-10-09 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('storage_url', models.URLField()),
                ('checksum', models.CharField(max_length=128)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('encrypted', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backups', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='farms.farm')),
            ],
            options={
                'indexes': [models.Index(fields=['farm', 'created_at'], name='backup_farm_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='backup_nonempty_size')],
            },
        ),
    ]
