# Generated by Django 6.1.2 on 2026-10-09 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cattle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=100, unique=True)),
                ('calibration', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('capture_mode', models.CharField(choices=[('video', 'Video'), ('photo', 'Foto')], max_length=10)),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confidence_interval_min_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confidence_interval_max_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('body_condition_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurements.aimodel')),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='cattle.cattle')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='measurements.measurement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='measurements.device')),
            ],
        ),
        migrations.CreateModel(
            name='MorphometricMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphometrics', to='measurements.measurement')),
                ('measurement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='measurements.measurementtype')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleWeighing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('weighed_at', models.DateTimeField()),
                ('scale_type', models.CharField(max_length=100)),
                ('actual_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scale_weighings', to='cattle.cattle')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='measurements.scaleweighing')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scale_weighings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['cattle', 'captured_at'], name='measurement_cattle_capture_idx'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_weight_kg__gt', 0)), name='measurement_positive_weight'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_interval_min_kg__gte', 0), ('confidence_interval_max_kg__gte', models.F('confidence_interval_min_kg')), ('estimated_weight_kg__gte', models.F('confidence_interval_min_kg')), ('estimated_weight_kg__lte', models.F('confidence_interval_max_kg'))), name='measurement_confidence_interval_valid'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('body_condition_score__gt', 0)), name='measurement_positive_body_score'),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_level__gte', 0)), name='measurement_nonnegative_confidence'),
        ),
        migrations.AddConstraint(
            model_name='morphometricmeasurement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('measurement', 'measurement_type'), name='unique_active_morphometric_type'),
        ),
        migrations.AddConstraint(
            model_name='morphometricmeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='morphometric_nonnegative_value'),
        ),
        migrations.AddIndex(
            model_name='scaleweighing',
            index=models.Index(fields=['cattle', 'weighed_at'], name='scale_weighing_cattle_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='scaleweighing',
            constraint=models.CheckConstraint(condition=models.Q(('actual_weight_kg__gt', 0)), name='scale_weighing_positive_weight'),
        ),
    ]
